x-app-build: &app-build
    context: ..
    dockerfile: docker/Dockerfile
    args:
        ENV_FILE: .env

services:
    hoso_sv__app:
        image: hoso_sv
        build: *app-build
        container_name: hoso_sv__app
        restart: unless-stopped
        environment:
            CONTAINER_ROLE: app
        ports:
            - "${APP_PORT:-3002}:8000"
        volumes:
            - ../storage:/var/www/html/storage
