networks:
    qlvb_network:
        driver: bridge

services:
    qlvb_nginx:
        image: nginx:alpine
        container_name: qlvb_nginx
        restart: unless-stopped
        tty: true
        ports:
            - "3005:80"
        volumes:
            - ../:/var/www/app/
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - qlvb_vite
            - qlvb_php
        networks:
            - qlvb_network

    qlvb_php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: qlvb_php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes:
            - ../:/var/www/app
        networks:
            - qlvb_network

    qlvb_vite:
        image: node:18
        container_name: qlvb_vite
        working_dir: /var/www/app
        volumes:
            - ../:/var/www/app
        command: sh -c "npm install && npm run build"
        networks:
            - qlvb_network
